{{- if .Values.ingress.enabled -}}
{{- $fullName := include "typebot.fullname" . -}}
{{- $builderServiceName := include "typebot.builder.name" . -}}
{{- $viewerServiceName := include "typebot.viewer.name" . -}}
{{- $builderServicePort := .Values.builder.service.port -}}
{{- $viewerServicePort := .Values.viewer.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "typebot.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- with .Values.ingress.hosts.builder }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ $builderServiceName }}
                port:
                  number: {{ $builderServicePort }}
          {{- end }}
    {{- end }}
    {{- with .Values.ingress.hosts.viewer }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ $viewerServiceName }}
                port:
                  number: {{ $viewerServicePort }}
          {{- end }}
    {{- end }}
{{- end }} 