apiVersion: v1
kind: Secret
metadata:
  name: {{ include "typebot.fullname" . }}
  labels:
    {{- include "typebot.labels" . | nindent 4 }}
type: Opaque
data:
  # Encryption Secret
  {{- if .Values.typebot.encryption.existingSecret }}
  # Will be fetched from existing secret
  {{- else }}
  ENCRYPTION_SECRET: {{ .Values.typebot.encryption.secret | b64enc | quote }}
  {{- end }}
  
  {{- if and (eq .Values.externalStorage.type "gcp") (not .Values.externalStorage.gcp.existingSecret) }}
  # GCP Credentials
  GOOGLE_APPLICATION_CREDENTIALS: {{ .Values.externalStorage.gcp.credentials | b64enc | quote }}
  {{- end }} 