name: Release Helm Chart

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - '.github/workflows/release.yaml'
  pull_request:
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - '.github/workflows/release.yaml'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Add Helm dependency repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Lint Helm chart
        run: helm lint .

      - name: Validate dependencies
        run: helm dependency build

      - name: Run Helm template
        run: |
          helm template --debug typebot . \
            --set typebot.encryption.secret=test-secret \
            --set typebot.nextauth.url=https://test.com \
            --set typebot.viewerUrl=https://test-viewer.com
  
  release:
    if: github.event_name != 'pull_request'
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Add Helm dependency repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "typebot-helm-chart-{{ .Version }}"
        with:
          charts_dir: "." 